#!/bin/sh

# Check golang files are staged.
staged_golang_files=$(git diff --cached --name-only | grep '.go$')

if [ -z "$staged_golang_files" ];then
  exit 0
fi

# Run golangci-lint
result=$(golangci-lint run ./...)

if [ $? -ne 0 ];then
  echo '[NG] Golangci-lint'
  echo $result
  exit 1
fi

# Run go test
result=$(go test ./...)

if [ $? -ne 0 ];then
  echo '[NG] Go test'
  echo $result
  exit 1
fi
