name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup the Golang environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run the tests
        run: go test ./...

      - name: Measure the test coverages
        run: go test -cover ./...

      - name: Run the benchmarks
        run: go test -bench=. ./...
